import fs from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";

/**
 * Loader for the weekly agenda proposals (scripts/propose-agenda.mjs
 * output under proposals/agenda/<runId>/<case>.md). Proposals are ideas,
 * not content: nothing here enters the ledger, and the page that renders
 * them says so. The parser targets the exact format renderProposalFile
 * emits (the roundtrip is pinned by tests); a block that does not parse
 * is skipped and counted, never guessed at, and never breaks the build —
 * a malformed proposal is a lost suggestion, not a lost site.
 */

export interface AgendaProposal {
  kind: string;
  title: string;
  question: string;
  closestExisting: string[];
  gap: string;
  wouldSettle: string;
  effortTier: string;
  /** Bench panel score, when the run has been scored (scores.yaml). */
  score?: ProposalScore;
  /** Study id when an advancing proposal's freeze has been drafted. */
  draftedAs?: string;
}

export interface ProposalScore {
  /** Seats voting "high" for expected information gain. */
  highs: number;
  /** Advancement under the 4-of-5-with-no-concerns rule (studies only). */
  advances: boolean;
  /** Substantiated constitutional concerns, verbatim, seat-labeled. */
  concerns: string[];
  /** One entry per seat: "Seat label: high|medium|low|failed". */
  seats: string[];
}

export interface ProposalFile {
  caseSlug: string;
  runId: string;
  date: string;
  model: string;
  promptVersion: string;
  proposals: AgendaProposal[];
  skippedBlocks: number;
}

export interface ProposalRun {
  runId: string;
  date: string;
  files: ProposalFile[];
}

const AGENDA_DIR = path.join(process.cwd(), "proposals", "agenda");

/** Parse one proposal file body (format: scripts/lib/agenda-propose.mjs). */
export function parseProposalFile(caseSlug: string, text: string): ProposalFile {
  const meta = {
    runId: text.match(/runId (\S+?),/)?.[1] ?? "unknown",
    date: text.match(/^# Agenda proposals — .+ — (\d{4}-\d{2}-\d{2})/m)?.[1] ?? "unknown",
    model: text.match(/Generated by (.+?), runId/)?.[1] ?? "unknown",
    promptVersion: text.match(/promptVersion (\S+?),/)?.[1] ?? "unknown",
  };
  const proposals: AgendaProposal[] = [];
  let skippedBlocks = 0;
  const blocks = text.split(/^## /m).slice(1);
  for (const block of blocks) {
    const head = block.match(/^\d+\. \[([a-z-]+)\] (.+)$/m);
    const question = block.match(/\*\*Question \/ truth condition:\*\* ([\s\S]+?)\n\n/)?.[1];
    const closest = block.match(/\*\*Closest existing:\*\* (.+?) — ([\s\S]+?)\n\n/);
    const wouldSettle = block.match(/\*\*What it would settle:\*\* ([\s\S]+?)\n\n/)?.[1];
    const effort = block.match(/\*\*Effort:\*\* (\S+)/)?.[1];
    if (!head || !question || !closest || !wouldSettle || !effort) {
      skippedBlocks += 1;
      continue;
    }
    proposals.push({
      kind: head[1],
      title: head[2].trim(),
      question: question.replace(/\s+/g, " ").trim(),
      closestExisting: closest[1].split(",").map((s) => s.trim()),
      gap: closest[2].replace(/\s+/g, " ").trim(),
      wouldSettle: wouldSettle.replace(/\s+/g, " ").trim(),
      effortTier: effort.trim(),
    });
  }
  return { caseSlug, ...meta, proposals, skippedBlocks };
}

/**
 * Bench scores for one run dir (scores.yaml, written by
 * scripts/score-agenda.mjs), keyed by proposal title within a case.
 * Absent file = the run predates scoring or is not yet scored; proposals
 * render without a score strip, never with a guessed one.
 */
function loadRunScores(dir: string): Map<string, ProposalScore> {
  const scoresPath = path.join(dir, "scores.yaml");
  const out = new Map<string, ProposalScore>();
  if (!fs.existsSync(scoresPath)) return out;
  let parsed: unknown;
  try {
    parsed = parseYaml(fs.readFileSync(scoresPath, "utf8"));
  } catch {
    return out; // a malformed scores file loses the strip, not the page
  }
  const tallies = (parsed as { tallies?: unknown })?.tallies;
  if (!Array.isArray(tallies)) return out;
  for (const t of tallies) {
    if (typeof t?.title !== "string" || typeof t?.case !== "string") continue;
    out.set(`${t.case}\u0000${t.title}`, {
      highs: Number(t.highs ?? 0),
      advances: Boolean(t.advances),
      concerns: Array.isArray(t.concerns) ? t.concerns.map(String) : [],
      seats: Array.isArray(t.seats) ? t.seats.map(String) : [],
    });
  }
  return out;
}

/**
 * Which advanced proposals already have their freeze drafted: the Bench
 * drafter writes the proposal id into each freeze file's header comment,
 * so the repo itself is the registry (no side state).
 */
function loadDraftedFreezes(): Map<string, string> {
  const out = new Map<string, string>();
  const casesDir = path.join(process.cwd(), "content", "cases");
  if (!fs.existsSync(casesDir)) return out;
  for (const c of fs.readdirSync(casesDir)) {
    const sdir = path.join(casesDir, c, "studies");
    if (!fs.existsSync(sdir) || !fs.statSync(sdir).isDirectory()) continue;
    for (const f of fs.readdirSync(sdir).filter((f) => f.endsWith(".yaml"))) {
      const text = fs.readFileSync(path.join(sdir, f), "utf8");
      const m = text.match(/panel-advanced agenda proposal \(([^)]+)\)/);
      const id = text.match(/^id: (\S+)/m)?.[1];
      if (m && id) out.set(m[1], id);
    }
  }
  return out;
}

/** All proposal runs, newest first; [] when none exist yet. */
export function loadProposalRuns(): ProposalRun[] {
  if (!fs.existsSync(AGENDA_DIR)) return [];
  const drafted = loadDraftedFreezes();
  return fs
    .readdirSync(AGENDA_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()
    .reverse()
    .map((runId) => {
      const dir = path.join(AGENDA_DIR, runId);
      const scores = loadRunScores(dir);
      const files = fs
        .readdirSync(dir)
        .filter((f) => f.endsWith(".md") && f !== "report.md")
        .sort()
        .map((f) => {
          const pf = parseProposalFile(
            f.replace(/\.md$/, ""),
            fs.readFileSync(path.join(dir, f), "utf8"),
          );
          pf.proposals = pf.proposals.map((p, i) => ({
            ...p,
            score: scores.get(`${pf.caseSlug}\u0000${p.title}`),
            draftedAs: drafted.get(`${runId}/${pf.caseSlug}/${i + 1}`),
          }));
          return pf;
        })
        .filter((pf) => pf.proposals.length > 0 || pf.skippedBlocks > 0);
      const date = files[0]?.date ?? runId.slice(0, 10);
      return { runId, date, files };
    })
    .filter((run) => run.files.length > 0);
}
