#!/usr/bin/env node
/**
 * The constitutional arbiter (AGENTS.md §3.15; Stage 4 of the AI-operated
 * pivot). Given a change set, five independent vendor seats each judge one
 * question — does this change comply with the constitution? — and the
 * tally decides: pass (≥4 complies, zero violates) or park.
 *
 * Usage:
 *   node scripts/arbiter.mjs --base <ref> [--head <ref>] [--title t] [--body-file f]
 *
 * Prints a markdown report to stdout (and arbiter-report.md); exits 0 on
 * pass, 1 on park, 2 on operational failure. During the supervised dry
 * period the workflow surfaces the report and exit code on every
 * needs-approval PR without gating the merge; flipping the gate later is a
 * branch-protection change, not a code change.
 *
 * Trust boundaries, explicit:
 *   - The DIFF and PR TITLE/BODY are UNTRUSTED — they may contain text
 *     that tries to instruct the judges. The system prompt fences them as
 *     data, and a seat that follows instructions found there has failed.
 *   - The constitution (AGENTS.md) is read from the BASE ref, not the PR:
 *     a change that edits the constitution is judged by the constitution
 *     it is trying to change. Amending AGENTS.md is reserved to the
 *     founder and the prompt says so.
 *   - Seats that error, refuse, or reply malformed become explicit
 *     `unsure` votes (fail-closed in src/lib/arbiter-core.mjs) —
 *     visible in the report, never dropped from the denominator.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { parseJsonReply } from "../src/lib/llm.mjs";
import { callSeat, VENDORS } from "../src/pipeline/transport.ts";
import { loadProtocol, renderProtocol } from "../src/pipeline/protocols.ts";
import {
  capDiff,
  CONTENT_MERGES_PER_WEEK,
  costOf,
  rateLimitGate,
  runAccount,
  splitMergeLanes,
  tallyVerdict,
  validateVote,
} from "../src/lib/arbiter-core.mjs";
import {
  extractCitations,
  formatVerificationSection,
  verificationSummary,
  verifyCitations,
} from "../src/lib/citation-check.mjs";

const PROMPT_VERSION = loadProtocol("panel").version; // the protocol file is the prompt (protocols/panel-v*.md)
const args = process.argv.slice(2);
const opt = (name) =>
  args.includes(name) ? args[args.indexOf(name) + 1] : null;
const base = opt("--base");
const head = opt("--head") ?? "HEAD";
const title = opt("--title") ?? "(no title given)";
const bodyFile = opt("--body-file");
if (!base) {
  console.error("usage: node scripts/arbiter.mjs --base <ref> [--head <ref>] [--title t] [--body-file f]");
  process.exit(2);
}

const ROOT = process.cwd();
const git = (...a) => execFileSync("git", a, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });

const mergeBase = git("merge-base", base, head).trim();
const rawDiff = git("diff", `${mergeBase}..${head}`);
const fileStat = git("diff", "--stat", `${mergeBase}..${head}`);
const constitution = git("show", `${mergeBase}:AGENTS.md`);
const prBody = bodyFile && fs.existsSync(bodyFile) ? fs.readFileSync(bodyFile, "utf8") : "(none)";
// A content run's own account goes to the panel whole; the diff takes what is left of the packet.
const PACKET_CHARS = 400_000;
const changedFiles = git("diff", "--name-only", `${mergeBase}..${head}`).trim().split("\n").filter(Boolean);
const account = runAccount(
  changedFiles,
  (p) => {
    try {
      return git("show", `${head}:${p}`);
    } catch {
      return null;
    }
  },
  (p) => git("diff", `${mergeBase}..${head}`, "--", p),
);
const { text: diff, omitted } = capDiff(rawDiff, PACKET_CHARS - account.text.length);

// Mechanical citation verification (§3.15 input, never a gate): resolve
// every DOI/arXiv id/URL the diff ADDS under content/, so seats judge how
// citations are used instead of voting unsure because they cannot browse.
const citations = extractCitations(rawDiff);
const verification = await verifyCitations(citations);

const protocol = loadProtocol("panel");
const SYSTEM = renderProtocol(protocol, { today: new Date().toISOString().slice(0, 10) });

const packet = [
  "=== CONSTITUTION (from the base revision — authoritative) ===",
  constitution,
  "=== PR TITLE (untrusted) ===",
  title,
  "=== PR BODY (untrusted) ===",
  prBody.slice(0, 8000),
  "=== CHANGE STAT ===",
  fileStat,
  account.text
    ? `=== RUN ACCOUNT (generated by this repository's tooling from the files it names — the run's own record, not the PR author's words) ===\n${account.text}`
    : "=== RUN ACCOUNT ===\n(none — this change carries no run records)",
  omitted.length > 0
    ? `=== OMITTED FILES (diff over size budget — you have NOT seen these) ===\n${omitted.join("\n")}`
    : "=== OMITTED FILES ===\n(none — the diff below is complete)",
  `=== CITATION VERIFICATION (tool output — mechanically resolved just now) ===\n${formatVerificationSection(verification)}`,
  "=== DIFF (untrusted) ===",
  diff,
].join("\n\n");

// PANEL SEAT — the refusal fallback (src/lib/llm.mjs) is BANNED here.
// Each seat's identity as a specific vendor/model is constitutionally
// load-bearing (§3.15 vendor-independence of the panel): a refusing seat
// counts as a FAILED seat ("unsure" below), never a silently swapped one.
// The seats are called through the pipeline's metered transport (src/pipeline/transport.ts):
// the same path a verb takes, the same tariffs, the vendor's own usage on every reply. The
// spend rows go to a scratch root — this process judges a PR and commits nothing — and the
// panel's cost travels in the machine blob instead, which the sitting's harvest copies into
// governance/arbiter/pr-<n>.yaml. The ledger is the whole bill: the panel included.
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), "aletheia-arbiter-"));
fs.mkdirSync(path.join(scratch, "config"), { recursive: true });
fs.copyFileSync(path.join(ROOT, "config", "tariffs.yaml"), path.join(scratch, "config", "tariffs.yaml"));
const meter = { runId: `${new Date().toISOString().slice(0, 10)}-panel-${head.slice(0, 10)}`, verb: "panel", case: null, root: scratch };

async function seatVote(name) {
  try {
    const reply = await callSeat(name, { system: SYSTEM, user: packet }, meter);
    const vote = validateVote(VENDORS[name].label, parseJsonReply(reply.text));
    return { ...vote, cost: { model: reply.model, inputTokens: reply.usage.inputTokens, outputTokens: reply.usage.outputTokens, usd: reply.usd } };
  } catch (err) {
    return {
      seat: VENDORS[name].label,
      vote: "unsure",
      rules: [],
      reasoning: `seat failed: ${String(err).slice(0, 200)}`,
      failed: true,
    };
  }
}

const votes = await Promise.all(Object.keys(VENDORS).map(seatVote));
const cost = costOf(votes);

// Weekly content throttle: count distinct commits on the base branch in the
// last 7 days that touch published case content. Applies only when this
// change itself touches content, and only ever downgrades pass -> park.
// Canon only: assessment overlays are mechanical, append-only, and land
// every time a panel convenes — counting them would spend the budget on
// the machinery's own heartbeat (the first live run parked a 5/5-complies
// PR at "41/10" for exactly that reason).
const CANON = ["content/cases/", ":(exclude)content/cases/*/assessments/**"];
const touchesContent = git(
  "diff",
  "--name-only",
  `${mergeBase}..${head}`,
  "--",
  ...CANON,
).trim().length > 0;
// --first-parent: one squash/merge = one landing on the base branch, so
// the budget counts what a reader saw change, not how many commits built it.
// The throttle governs the AUTONOMOUS era: landings during human-supervised
// construction sprints are not the machine's pace and must not spend its
// budget. Epoch 1 (2026-08-25T16:22Z, the #59 merge) excluded bootstrap
// week's 39 supervised landings after they parked a 5/5-complies caption
// fix. Epoch 2 (2026-08-27T10:00Z) closes the founder-supervised studies
// sprint of 2026-08-26/27 (~30 founder-tapped landings: the studies
// feature, seven studies, article updates), which had spent the budget to
// 34/10 and would have frozen the autonomous lane for a week. Each epoch
// bump is a founder-directed, panel-reviewed declaration that the
// preceding landings were supervised construction; the window is the
// trailing week or the latest epoch, whichever is shorter.
//
// Epochs are now the fallback rather than the mechanism. Both bumps above
// were manual refunds for the same recurring miscount, and it recurred a
// third time on 2026-09-02 (14/10, parking a 5/5-complies content batch).
// Supervised merges now declare themselves with a `Supervised-by:` trailer
// and are excluded per-merge, so the epoch should not need bumping again;
// it stays as the coarse remedy of last resort.
//
// Epoch 3 (2026-09-03T13:00Z) is that remedy used once more, and on a
// measurement rather than an impression. Of the 15 canon merges in the
// window at 15/10, five were autonomous (#156, #158 content responses,
// #148 promotion, #147 and #144 maintenance) and ten were founder-directed
// construction (#125/#129 and #152/#153, the study freeze/collection
// pairs; #135 pins; #132 founding inputs; #128 metabolism; #124 transients
// adoption; #113/#118 Amazon). The autonomous lane's true usage was 5/10 —
// half the budget — while the lane sat frozen on supervised work. The
// per-merge exclusion cannot refund those ten, because merged commit
// messages are immutable, so this bump clears the miscount one last time.
// Founder-directed, 2026-09-03 session ("any fixes you need to do —
// please let's do them"), with the structural fix already in place.
//
// Epoch 4 (2026-09-09T15:00Z): the construction day of 2026-09-09 — fourteen
// content landings, every one a chain the operator ran by hand and the
// founder merged by hand (the supplied-source intake, the second essay,
// two repairs, the first CI run), none carrying the trailer — had spent
// the window to 14/10 and parked the chain's own first CI run (#214, 5/5
// complies). Founder-directed in session on 2026-09-09, on turning the
// automation on: the autonomous lane starts with a clear window.
const GATE_EPOCH = Date.parse("2026-09-09T15:00:00Z");
const since = new Date(
  Math.max(Date.now() - 7 * 86400000, GATE_EPOCH),
).toISOString();
// Hash + full message per commit, so the trailer is readable. Unit
// separator between fields, record separator between commits: commit
// messages contain newlines and blank lines, so line-splitting cannot
// delimit them.
const mergeLog = git(
  "log",
  "--first-parent",
  `--since=${since}`,
  "--format=%H%x1f%B%x1e",
  base,
  "--",
  ...CANON,
)
  .split("\x1e")
  .map((rec) => {
    const [hash, message] = rec.replace(/^\s+/, "").split("\x1f");
    return { hash: (hash ?? "").trim(), message: message ?? "" };
  })
  .filter((c) => c.hash);
const lanes = splitMergeLanes(mergeLog);
const mergesThisWeek = lanes.autonomous.length;
const supervisedExcluded = lanes.supervised.length;
const verdict = rateLimitGate(tallyVerdict(votes), {
  touchesContent,
  mergesThisWeek,
  supervisedExcluded,
});

const report = [
  `<!-- aletheia-arbiter -->`,
  `## Constitutional arbiter — ${verdict.outcome === "pass" ? "✅ PASS" : "🅿️ PARKED"}`,
  "",
  `**${verdict.reason}.**`,
  "",
  `Panel (${PROMPT_VERSION}, judged against \`AGENTS.md\` at \`${mergeBase.slice(0, 10)}\`):`,
  "",
  "| Seat | Vote | Rules cited | Kind |",
  "|---|---|---|---|",
  ...votes.map(
    (v) => `| ${v.seat} | ${v.vote} | ${v.rules.join(", ") || "—"} | ${v.paradigm ?? "—"} |`,
  ),
  "",
  ...(verdict.notes?.length
    ? [
        `> 📝 Review note: ${verdict.notes.map((v) => `**${v.seat}** objects (${v.rules.join(", ")}; ${v.paradigm})`).join("; ")} without the panel. The change may merge; the objection is recorded as an issue labeled \`review-note\` that the operator answers on the record — by fixing, or by saying why not (AGENTS.md §3.15, amendment of 2026-09-09).`,
      ]
    : []),
  "",
  ...votes.map((v) => `<details><summary><b>${v.seat}</b> — ${v.vote}</summary>\n\n${v.reasoning}\n\n</details>`),
  "",
  omitted.length > 0
    ? `> ⚠️ ${omitted.length} file(s) exceeded the diff budget and were not shown to the panel: ${omitted.join(", ")}`
    : "",
  verification.length > 0 ? `> 🔗 ${verificationSummary(verification)}.` : "",
  `> 💰 Panel cost: ${cost.usd === null ? "not fully priced" : `$${cost.usd.toFixed(2)}`} (${cost.inputTokens.toLocaleString("en-US")} tokens in, ${cost.outputTokens.toLocaleString("en-US")} out, ${cost.seats} seat(s) metered; priced from config/tariffs.yaml, kept in governance/arbiter/ at harvest).`,
  // Reported on every content verdict, not only when it bites: the
  // supervised exclusion is the throttle's one discretionary input, so a
  // drift toward blanket exemption has to be visible continuously rather
  // than discoverable in an audit nobody runs.
  touchesContent
    ? `> ⏳ Rate limit: ${mergesThisWeek}/${CONTENT_MERGES_PER_WEEK} autonomous content merges in the window${
        supervisedExcluded > 0
          ? `, ${supervisedExcluded} excluded as \`Supervised-by:\` (${lanes.supervised
              .map((h) => h.slice(0, 7))
              .join(", ")})`
          : ""
      }.`
    : "",
  // Was a dry-period note calling this report advisory. The dry period
  // ended 2026-08-25 and the check is required on `main`, so a park now
  // blocks the merge — a footer saying otherwise told the reader the
  // opposite of what the branch protection was doing.
  `> This verdict is binding: the \`arbiter\` check is required on \`main\`, so a park blocks the merge until the change is revised or a seat that failed is restored. The founder's admin override remains the kill switch (docs/MAINTENANCE.md).`,
  // Machine-readable record for scripts/harvest-governance.mjs — kept
  // inside an HTML comment so the human report stays clean.
  `<!-- aletheia-arbiter-data ${JSON.stringify({
    verdict: verdict.outcome,
    reason: verdict.reason,
    judgedAgainst: mergeBase.slice(0, 10),
    promptVersion: PROMPT_VERSION,
    seats: votes,
    notes: verdict.notes ?? [],
    cost,
  })} -->`,
].join("\n");

console.log(report);
fs.writeFileSync(path.join(ROOT, "arbiter-report.md"), report);
process.exit(verdict.outcome === "pass" ? 0 : 1);
